version: '3'

services:
  app:
    container_name: API
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code


  db:
    image: postgres:15.3
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${FSTR_DB_NAME}
      - POSTGRES_USER=${FSTR_DB_LOGIN}
      - POSTGRES_PASSWORD=${FSTR_DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  db-data:
