"""Migration

Revision ID: c4669cfc7854
Revises: 
Create Date: 2023-08-01 10:45:26.190501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4669cfc7854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pereval_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pereval_add',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('coords_id', sa.Integer(), nullable=False),
    sa.Column('beauty_title', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('other_titles', sa.String(length=255), nullable=False),
    sa.Column('connect', sa.Text(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('level_winter', sa.String(length=255), nullable=True),
    sa.Column('level_summer', sa.String(length=255), nullable=True),
    sa.Column('level_autumn', sa.String(length=255), nullable=True),
    sa.Column('level_spring', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coords_id'], ['coords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pereval_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pereval', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('data_added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pereval'], ['pereval_add.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pereval_images')
    op.drop_table('pereval_add')
    op.drop_table('users')
    op.drop_table('pereval_areas')
    op.drop_table('coords')
    op.drop_table('activities_types')
    # ### end Alembic commands ###
